# Bottlenecks and capacity 

How many arithmetic problems can you do simultaneously? Although your brain contains more than 80 billion neurons, if you are asked to multiply two two-digit numbers together, you will only be able to do one at a time [@oberauerAccessInformationWorking2002, @zylberbergBrainRouterCortical2010a]. Of course, this is not a task that most of us do daily. Reading, however, is such a task. If I showed you twenty words on a page, how many could you read simultaneously? A large body of psychological research suggests that humans can read at most only a few words at a time, and some claim that we can only read one word at a time [@whiteEvidenceSerialProcessing2018; @reichleEncodingMultipleWords2009]. 

Some parts of the mind can process many things at once. In vision, early processing stages are massively parallel. Each bit of the retinal image has its own photoreceptors devoted just to it. In the primary visual cortex, individual neurons respond to larger regions, but collectively still process many regions at once, in parallel. 

A common example of a visual ability that appears to have a high simultaneous processing capacity is a certain kind of visual search. In some circumstances, we can quickly locate targets hidden in a large number of distractors. For example, try searching for the blue objects in the below display.

```{r, echo=FALSE, fig.cap = "", fig.height = 2.0, fig.width=2.5}
#bookdown-demo_files/figure-html/unnamed-chunk-9-1.png ?
library(ggplot2)
library(tibble)
pts<- expand.grid(x = seq(2,16,2), y = seq(2,16,2), type = c("distractor"))
jittr<-.4
pts$x <- pts$x + runif(length(pts$x))*jittr-jittr/2
pts$y <- pts$y + runif(length(pts$y))*jittr-jittr/2
pts$type <- as.character(pts$type)
pts$type[c(1,4,6,8,11,12,13,16,20,25,26,30,33,37,41,44,47,48,52,55,59,60)] <- "distractor2"
pts$type[c(13,26,46)] <- "target"

ymin<-600; ymax<-2000
ggplot(pts,aes(x=x,y=y, color=type)) + geom_point(size=6)  +  theme_void() + theme(legend.position = "none")
#+ ylim(ymin,ymax)
```

Locating the three blue objects should be very easy. One reason is that our visual systems process each of the shapes simultaneously, and makes the locations of the blue objects available when you choose to attend to blue. Some brain areas, however, do not have neurons that can recognize objects dedicated to each bit of the visual field. Instead, their simultaneous processing capacity is limited. The processes required to recognize words are an example.

For limited capacity processes, something is needed to pick out, from a crowded scene, just one or a few objects for these areas to recognize. We call this something *selective attention*. Different visual abilities seem to have different capacities, and it is not at all clear that a common selective attention process is responsible for gating all of their inputs.

@duncanSelectiveAttentionOrganization1984 was interested in how many objects we can process at a time. He found that accuracy for making a simple visual judgment about an object was much worse when one needed to simultaneously make a judgment about another. For example, participants were asked to judge whether a briefly-presented rectangle was small or large and also judge whether a simultaneously presented line was dotted or dashed. Performance was  worse in the two-object condition even in comparison to a single-object condition where two judgments also needed to be made. The participants had to make either two judgments about a single object or one judgment about one object and the second judgment about a different object. To Duncan, his finding that performance was substantially worse in the two-object condition indicated the existence of a bottleneck at a stage that processes objects. He wrote that 

> Findings support a view in which parallel, preattentive processes serve to segment the field into separate objects, followed by a process of focal attention that deals with only one object at a time.

This conclusion was a bit of an over-reach. Performance was better than one would expect if only one object were processed, unlike what has been found for word processing. Duncan could explain that by saying that the presentation time was adequate for focal attention to, on *some* trials, process more than one object. Alternatively, however, it may be that the relevant processes *can* handle two objects at a time, but just does so more poorly than for one object. Work that credibly claims that a visual ability is truly limited to one object at a time is hard to find; the reading of words may be an exception.

<!-- One concern with this conclusion was that the results might be explained by a bottleneck on the number of spatial locations that participants needed to process rather than the number of locations. However, subsequent work was more effective at spatially overlapping two objects, which diminished this concern [@blaserTrackingObjectFeaturespace2000]. 
-->

## The tracking bottleneck

### There is no hard limit on the number of objects that people can track

Like reporting on the features of objects, the processing needed to covertly track objects also has very limited capacity. Participants asked to track several objects perform much worse than if they are asked to track only a few objects. <!--This suggests a capacity limit for tracking, in contrast to those visual judgments that seem to tap more directly into the massively-parallel processing performed by the early visual system.-->

The tracking bottleneck implied by such results is frequently portrayed in the literature as being a hard limit, or close to it. @doranRoleVisualAttention2010, for example, claim that "the main finding" from the object tracking literature "is that observers can accurately track approximately four objects and that once this limit is exceeded, accuracy declines precipitously."  <!--cites Pylyshyn Storm 1989-->, @fougnieDistinctCapacityLimits2006 write that "People’s ability to attentively track a number of randomly moving objects among like distractors is limited to four or five items", @piazzaNeurocognitiveStartupTools2011 state that "One of the defining properties of this system is that it is limited in capacity to three to four individuals at a time" <!-- which cites Scholl's objects paper which makes the claim of 4 FINSTs but backs it up only with STM etc. type studies -->, @alvarezHowManyObjects2007 that ""researchers have consistently found that approximately 4 objects can be tracked", @chesneyEvidenceSharedMechanism2011 write that "people typically can track four or five items"  <!--cites Pylyshyn 1989-->, and @vanderburgChangesNotDifferences2019 write that "participants can track about four objects simultaneously" <!-- (see Cavanagh & Alvarez, 2005, for a review; Pylyshyn & Storm, 1988)-->. In each of these cases, I have checked the evidence provided, or the papers cited, as well as the papers those papers cite. Each paper either provides no relevant evidence, or finds instead only a gradual decrease in performance as number of targets is increased with no discontinuity, nor even a conspicuous inflection point. For example, @oksamaMultipleObjectTracking2004 designated between two and six objects as targets, among twelve identical objects in total. After the objects moved around randomly for five seconds, one object was flashed repeatedly and participants hit a key to indicate whether they thought it was one of the targets. The proportion of trials in which participants were wrong increased steadily with target size, from 3% incorrect with two targets, to 16% incorrect with six targets. Note that even with six targets, participants were performing substantially better than would be expected if they could only track one or two and had to guess on the others.

Some of the spurious claims of a limit for tracking of about four objects seems to stem from wishful thinking by researchers that the capacity limit on various tasks might co-incide. The literature on numerosity perception had long found a discontinuity in performance for estimating the number of collections of more than about four objects [@jevonsPowerNumericalDiscrimination1871; @revkinDoesSubitizingReflect2008]. In the "subitizing range" of four or fewer objects, performance is approximately as good for rapidly counting four objects as it is for two or one. This appears to have motivated researchers to suggest, sometimes with little evidence, that other tasks show the same phenomenon of a very high performance below a particular number of objects, with a steep decline after. For example, in the Introduction of @bettencourtSharedFilteringProcesses2011, the authors write "both processes [visual short-term memory and MOT] showing an equivalent four-object limit".

<!--Pylyshyn et al. 1994: "possible to track about four randomly moving objects" even though earlier in that paper he says "at least four" and acknolwedges it depends on trajectories etc. -->
<!-- Franconeri & Alvarez: "researchers have consistently found that approximately 4 objects can be tracked (Intriligator & Cavanagh, 2001; Pylyshyn & Storm, 1988; Yantis, 1992). The similarity of these estimates, combined with the frequency with which 4-item limits arise in other attention tasks, suggests the possibility that there is a “magical number 4” in visual attention (Cowan, 2001; Pylyshyn, 1989)." -->
<!-- Papers I have checked for the 4-object claim: Cowan, 2001 claimed it for MOT, citing Pylyshyn et al. 1994, which does say "experiments showing that observers can simultaneously track some three to five identical target items" but then when he describes the studies he doesn't say they show that, even though in the discussion he says "One is that it is possible to track about four randomly moving objects" -->
<!-- In some cases the problem stems from Scholl Pylyshyn Feldman paper that devised the effective tracking capacity measure assuming 100% accuracy for one object and delivering a single number, often 4, for effective number tracked-->
<!--  Alvarez & Franconeri (2007) in their Introduction claims that Pylyshyn & Storm 1988 and Yantis 1992 and Intriligator & Cavanagh 2001 all said you can only track up to 4 objects, but neither said any such thing, it seems from my reading of those papers, e.g.  Pylyshyn & Storm 1988 only went up to 5 out of 10 and there was gradual decrease in performance all the way through. -->

<!-- https://psyc2016.whatanimalssee.com/bottlenecks.html#a-bottleneck-for-object-judgments -->

### There is no real limit on the *effective* number of objects that people can track

A very widespread idea in the 

Many cognitive psychology researchers, even those that have never read a paper

ill-formed question?

This has been the dominant framing since the beginning of MOT research, when Pylyshyn suggested that tracking was limited by the number of discrete pointers or FINSTs that people have. But the underlying reason for variation in MOT performance may not be due to variation in number of FINSTs or some other such capacity, but rather due to variation in peoples' tracking speed limit, spatial interference, or temporal interference. This does not seem to have been properly investigated.

This question is a mistake. 

Working off the dominant framing, that each person does have a specific number of targets they can track which determines percent correct for each level of number of targets, some MOT researchers report what @schollWhatVisualObject2001 called the "effective number of items tracked". The associated formula, refined by @hullemanMathematicsMultipleObject2005a allows researchers to calculate the effective number of items tracked based on accuracy in an individual condition, given the number of targets and distractors in that condition. This does provide a useful summary of the data, but researchers should take more care to avoid taking it literally.

@meyerhoffIndividualDifferencesVisual2020 tested fifty participants and for each one calculated the effective number of items tracked, for a display with four targets and four distractors, the modal effective number of items tracked was around two, but a substantial proportion of participants's came in at three targets or one target, and a few scored close to zero effective items tracked. 

Unfortunately, in the data of @meyerhoffIndividualDifferencesVisual2020, like that of many others, there is no way to know how much of the variation between individuals is due to motivation rather than ability. Measuring motivation is not easy, but researchers should at least include what are sometimes called attention checks or catch trials to allow exclusion of participants who show clear evidence of not reading the instructions carefully or frequently not paying attention.

The statements in the literature such as "participants can track four moving objects" also mislead readers in another way. The finding that participants can track at least four objects with reasonable accuracy is restricted to particular object speeds [@alvarezHowManyObjects2007; @holcombeExhaustingAttentionalTracking2012] and spacings [@franconeriEvidenceSpeedLimit2008; @holcombeObjectTrackingAbsence2014].

The particular number of objects that can be tracked with reasonable accuracy is thus highly dependent on conditions. Still, it is clear that this number is small relative to the number of objects that are simultaneously processed by early stages of the visual system. So, what aspect exactly of tracking imposes this limitation?
