# Unitary cognition (System B) {#Cequals1}

Successful performance of a multiple object tracking task may be assisted by two resources. This worries me. One resource is the one that researchers typically believe they are studying. This resource can process multiple targets simultaneously, even if it processes them more poorly than it processes a lone target. This is the resource that most researchers, including myself, use tracking to study. However, the mind also has another resource that likely contributes to tracking performance.

The processes that support our ability to explicitly reason, often referred to as System 2 in cognitive psychology, can assist performance in many tasks. But this system is very limited in capacity - some cognitive researchers think it can only operate on one thing at a time [@oberauerAccessInformationWorking2002]. This may be what prevents us from doing, for example, more than one 2-digit mental multiplication problem at a time. But this also means one can apply System 2 to tracking a single target, for example to use what you've learned about object trajectories to predict future positions. The "System 2" concept was developed within cognitive psychology to distinguish between two types of cognitive processing. As opposed to the lower-level processing thought to allow people to simultaneously track multiple targets, here I want a term that refers to aspects of cognition that have a capacity of approximately one object. Because I know of no existing term, I will refer to it with the phrase "System B". 

## An inconvenient possibility

That tracking performance might reflect a combination of two systems, System B and a more low-level and possibly higher-capacity tracking process, complicates the interpretation of many experiments. Indeed, it makes the results trumpeted by some tracking papers fairly uninteresting, because the results could be caused entirely by our cognitive abilities (System B) operating on a single target, rather than reflecting the tracking resource that we seem to be able to distribute to multiple targets. MOT researchers have sometimes contented themselves with showing that a factor makes some non-zero difference to performance, as if the only criterion for newsworthiness is that the associated p-value is less than 0.05. But in a task involving tracking several targets, a factor that has only a small effect could be explained by System B operating on just one target. As an example of evidence that such a capacity=1 process may contribute to visual cognition, @xuCapacityVisualFeatures2015 found that participants could mentally rotate only a single part of a multi-colored shape.

Imagine that a study finds that people track multiple objects more accurately if they move on predictable trajectories than on unpredictable trajectories. This has in fact been found repeatedly, first by @fencsikRoleLocationMotion2007. Could the result be be due to our System B thought processes operating on just one target, rather than it revealing anything about the multiple-object tracking processes?  Ruling this out requires sophisticated methods, such as showing that the predictable-trajectory advantage applies independently in each hemifield, as we will see in Chapter \@ref(twoBrains), or that the effect shows some other idiosyncrasy of tracking, such as inability to work with individual locations within a moving object, as described in Chapter \@ref(objects). Researchers have typically not done this, unfortunately, but what has been done is to assess the capacity limit of the underlying process. The resulting findings suggest that the use of motion information during tracking may be subject to a more severe capacity limit than the use of position. In conditions where participants can use position information to accurately track four or five targets, they can only use motion information for one or two of the targets [@howeMotionInformationSometimes2012; @luuExtrapolationOccursMultiple2015; @wangRoleKinematicProperties2021]. Perhaps the predictability of trajectories can be taken advantage of only by the extended cognitive processing of an object that System B is capable of. 

My essential point is that even when participants are asked to track several targets, one can expect that System B is contributing to overall performance, even if they are only involved in the processing of one of the targets. By using our capacity for reasoning and symbol manipulation, we can perform a wide array of arbitrary tasks, so we should not be surprised by the ability to track a *single* target. We have a visual system that makes the position and direction of motion of objects on our retina available to cognition, and by using our ability to think about where an object is going and deliberately moving our attention to a future anticipated location, we might muddle through to success at tracking a single object. Thus, when researchers contrast tracking performance with different numbers of targets, one reason for the decline in performance may be that System B type processes are, in each condition, processing only a single target, so performance declines rapidly with target load.

<!-- Unfortunately, researchers frequently neglect the fact that two sorts of mental abilities likely contribute to MOT performance: one or some limited in capacity to just a single target, and others with a greater processing capacity.  -->

