# Progress and recommendations {#recommendations}

In Section \@ref(intro) of this book, I flagged four important findings from the literature, which I subsequently went into in depth to show that they are quite well supported. Here they are again:

1. Target load has little effect on spatial interference, whereas temporal interference increases steeply with target load (Section \@ref(spatialInterference)).
1. Predictability of movement paths benefits tracking, but only for one or two targets, not for more (Section \@ref(Cequals1)).
1. Tracking capacity is hemifield specific: one can double capacity by dividing targets between the hemifields (Section \@ref(twoBrains)).
1. When tracking multiple targets, people often don't know which target is which, and updating of non-location features is poor (Section \@ref(identity)).

Something that's not really a finding about how tracking works, but is another important result is how good the MOT task typically is: its high test-retest reliability, of approximately .8 or .9, which is among the highest of attentional tasks (Section \@ref(abilities)). The outlook for future work, then, is positive both from the prospect of new results being credible (because with a non-noisy task, less data is needed to have high statistical power) and for the use of MOT as a tool to study individual differences.

## How far have we come?

Pylyshyn's FINST theory was the very first theory of tracking, and was published way back in 1988. Despite hundreds of published studies since then, still today (at the time of writing), Pylyshyn's FINST theory is the featured theory on the "multiple object tracking" Wikipedia page [@wikipediaeditorsMultipleObjectTracking2021], and it is frequently invoked in the scholarly literature as well. However, some main features of the theory have been rebutted [@schollWhatHaveWe2008]. Core to Pylyshyn's theory was the idea that tracking is mediated by a fixed set of discrete, preattentive indices. As we have seen, however, as speed increases, the number of targets that can be tracked rapidly decreases, to one target, which is hard (although not impossible) to explain with a fixed set of discrete indices [@alvarezHowManyObjects2007; @holcombeExhaustingAttentionalTracking2012].

FINST theory also claimed that the tracking process was preattentive, but dual-task studies indicate that tracking draws on attentional resources shared with some other tasks  [@oksamaPositionTrackingIdentity2016; @alnaesPupilSizeSignals2014] (I did not have space in this Element to review these). I should add, however, that such studies do not seem to have ruled out the possibility that these findings were caused entirely by a process with a capacity of only one object (what I have called System 2) rather than the hemifield-specific tracking processes. This could be resolved by testing for the the hemifield specificity of the findings <!--FUTURE-->, but this does not appear to have not been done. A further prediction of Pylyshyn's theory was that participants should be aware which target is which among the targets they are tracking. Pylyshyn himself found strong evidence against this, and the evidence  for poor updating of target identities has increased since then.

<!--Although CDA findings suggest there is something tracking number of objects rather than resources expended @drewVogel @balabanObjectRepresentationsVisual2016, I don't know that it supports a limit on this -->
At the time of writing, Pylyshyn's FINST theory is the featured theory on the "multiple object tracking" Wikipedia page [@wikipediaeditorsMultipleObjectTracking2021], and it is frequently invoked in the scholarly literature as well. However, some main features of the theory have been rebutted [@schollWhatHaveWe2008]. Core to Pylyshyn's theory was the idea that tracking is mediated by a fixed set of discrete, preattentive indices. As we have seen, however, as speed increases, the number of targets that can be tracked rapidly decreases, to one target, which is hard (although not impossible) to explain with a fixed set of discrete indices [@alvarezHowManyObjects2007; @holcombeExhaustingAttentionalTracking2012].

FINST theory also claimed that the tracking process was preattentive, but dual-task studies indicate that tracking draws on attentional resources shared with some other tasks  [@oksamaPositionTrackingIdentity2016; @alnaesPupilSizeSignals2014] (I did not have space in this Element to review these). I should add, however, that such studies do not seem to have ruled out the possibility that these findings were caused entirely by a process with a capacity of only one object (what I have called System 2) rather than the hemifield-specific tracking processes. This could be resolved by testing for the the hemifield specificity of the findings <!--FUTURE-->, but this does not appear to have not been done. A further prediction of Pylyshyn's theory was that participants should be aware which target is which among the targets they are tracking. Pylyshyn himself found strong evidence against this, and the evidence  for poor updating of target identities has increased since then.

<!--Although CDA findings suggest there is something tracking number of objects rather than resources expended @drewVogel @balabanObjectRepresentationsVisual2016, I don't know that it supports a limit on this -->

## Recommendations for future work

From our journey through the literature, various recommendations for multiple object tracking researchers have emerged, and here are three that I believe to be particularly important: 

* To dilute the influence of capacity-one System 2 processing, use several targets, not just two or three. But remember that even with several targets, a small effect could be explained by a capacity-one process. Test for hemifield specificity as that can also rule out a capacity-one process.

* Always test for hemifield specificity! In addition to it helping to rule out a factor having its effect only on a capacity-one process, we know very little about what limited-capacity brain processes are hemisphere-specific, so any results here are likely to be interesting.

* As we have seen, MOT is a complex task, so it's difficult to interpret individual differences in the overall task or how they will translate to other tasks. Individual-difference studies should use task variations that help isolate the component processes that contribute to overall success or failure, such as spatial interference, temporal interference, and cognitive processing.

<!--The effect increases with retention interval, and may be a more cognitive mechanism, as it has been suggested that  Rep- resentational momentum occurs in memory for implied motion stimuli and  neither of which elicits pursuit eye movements.-->


To further highlight how much we have learned in the last thirty-odd years, next I will describe how much findings have allowed us to disconfirm multiple aspects of the first and most influential theory of tracking, Zenon Pylyshyn's FINST theory.

<!--
Top misconceptions about MOT
* its capacity limit is around 4 items.(this has been used to argue that it has a similar capacity limit to visual working memory (Cowan, 2001).)
* "While the most intuitive model of multiple object tracking would involve storing the locations of targets in spatial memory, then moving attention in turn as quickly as possible to each target to update its location, this class of model is unable to account for MOT performance (Pylyshyn & Storm, 1988; Vul et al., 2009)"

Reading your paper also gave me an idea to have a Common Misconceptions section for the Cambridge Element.  One might be that the capacity limit on VWM and MOT coincide (what you refer to as "The most striking link between the two tasks is that they seem to have a similar capacity limit of around four items (Cowan, 2001)". I totally agree that it is striking and so it is natural to think it means something, but while I don't know much about VWM, the capacity limit for MOT is determined by the speeds, spatial proximities,and temporal frequencies used, so as you know the limit can be anything between zero and more than ten.  It is true that the speeds most often used yield a capacity limit of around four, but I haven't seen any argument for why the commonly used speeds/spatial proximities/temporal frequency combination is more special than the other possibilities. I guess one could argue that researchers set those parameters to resemble an intuition for what real-world tasks are like, but even if they got that right, I'm not sure the same is true for VWM setups, or what that would imply for underlying ability structures. It seems to me one would have to do some kind of ideal observer (really, ideal thinker) model with the same assumptions that can model both common VWM and common MOT tasks, and show that the same level of ability in fundamental processes underlying each would yield the same capacity limit of four in both cases.

Thus, while many potential athlete users may imagine that a test of attention tests how long they can pay attention, this is not likely to be the reason for differences among people on MOT performance. -->



## Topics not covered by this book

Many topics that I originally planned to cover could not be included in this Element (I was given a word limit by the publisher). Some of the most important are whether tracking operates in a retinotopic, spatiotopic, or configural representation (see [@yantisMultielementVisualTracking1992; @billHierarchicalStructureEmployed2020; @howeCoordinateSystemsUsed2010; @meyerhoffDistractorLocationsInfluence2015b; @liuMultipleObjectTrackingBased2005; @maechlerAttentionalTrackingTakes2021]), the role of distractors and possible distractor suppression, the role of surface features [@papenmeierTrackingLocationFeatures2014], and the literature on dual-task paradigms, although a few dual-task papers were mentioned along the way [e.g., @alvarezMultielementVisualTracking2005]. <!--The use of velocity signals -->

If your favorite topic is not covered, possibly you can take some consolation in the fact that my own favorite topic, the temporal limits on tracking [@holcombeSplittingAttentionReduces2013; @roudaiaDifferentEffectsAging2017; @howardPositionRepresentationsLag2011], also was not covered. I hope to address this topic, which has major implications for what the tracking resource actually does during tracking, and whether processing is serial or parallel, in a separate manuscript. <!--early work had concluded that MOT could not reflect serial position sampling [@pylyshynTrackingMultipleIndependent1988; @yantisMultielementVisualTracking1992], this recently has been questioned, and now is a favored account of tracking in some circumstances, as reviewed in Chapter \@ref(serialOrParallel).-->

* For computational modelling, I don't recommend modelling only data from standard, fairly unconstrained trajectories, as such data may not constrain models enough. Show your model successfully mimics both spatial crowding and temporal interference effects, including that temporal interference is more resource-intensive than spatial interference. Another strategy is to model large sets of data at an individual trial level; previous efforts seem to have modelled data from only one or a few different MOT experiments.


<!--
## Dual-task OUT OF SCOPE

Another experiment indicates that trying to remember object identities can actually interfere with the ability to track [@fougnieDistinctCapacityLimits2006]. This is consistent with the possibility that position tracking and object feature updating rely on distinct mental capacities. MOT interfered with VWM a lot although not as much as VWM interfered with VWM

" though both search and MOT can be highly atten- tionally demanding, they may do so via demands on partially independent attentional subsystems. In particular, visual search may interfere dramati- cally with scene encoding because both processes rely heavily on the same underlying ventral identification-based form of attention. In contrast, MOT fails to interfere with scene encoding more than central executive tasks because MOT relies primarily on a different underlying type of visual attention, one that is dorsal and individuation based. This distinction may also help to explain why MOT and search interfere with each other so little (Alvarez et al. 2005): They may both be highly attention-demanding, yet they may draw on fundamentally different forms of attention. Similarly, this may help to explain why observers are relatively poor at encoding surface features of objects in MOT—including those of tracked targets (see, e.g., Bahrami 2003; Ko and Seiffert 2006; Scholl, Pylyshyn, and Franconeri 1999). "

Dual-task 

Alvarez, G.A., et al., Are mutielement visual tracking and visual search mutually exclusive? Journal of Experimental Psychology: Human Perception and Performance, 2005. 31(4): p. 643-667.

There seems to be an especially close link between MOT and subitizing
@trickAgeDifferencesEnumerating2003 observed that even very slow motion reduced
enumeration speed for stimuli containing 6–9 items, while
the enumeration of 1–4 items was not affected when items
were in motion. Similarly, @alstonSubitizationAttentionalEngagement2004
presented static and moving items, finding that faster and
more accurate enumeration occurred in the subitizing range
given the presence of moving items.

psilocybin seems to impair MOT but not visual working memory [@carterUsingPsilocybinInvestigate2005] 

Subitizing no bilateral advantage on accuracy, but that could be due to very high accuracy - when looking at response time, an advantage is found, although not clear it's as large as that for MOT @railoBilateralTwoitemAdvantage2014

"The results indicated that the number of items participants could subitize decreased by one for each item they tracked." @chesneyEvidenceSharedMechanism2011

 "concurrent performance of a MOT task and a VWM task still instilled substantial and load-dependent dual-task costs. " @fougnieDistinctCapacityLimits2006

@allenMultipletargetTrackingRole2006

object tracking in people with Williams Syndrome remains at the level of 4‐year‐olds, whereas the ability to remember multiple locations of static objects develops further. @ohearnDevelopmentalProfilesMultiple2010 

@howardVisualSpatialAttention2020 "for a purely spatial task, perceptual attention (TRACKING?) and working memory appear to recruit separate core capacity-limited processes."

@souzaContributionsVisualCentral2017 argued that VWM and MOT use different attentional resources." "Distracting visual attention, but not central attention, impaired MOT performance"
-->








