# Towards the real world

Object tracking findings from the laboratory should help us understand how humans perform in real-world situations. The change detection literature is an inspiring example of how lessons from a task can inform real-world practice. Without knowledge of change detection results, some practitioners, such as coaches of team sports, likely subscribed to the naive view of visual perception and attention that we are simultaneously aware of the identities of all the objects in a scene, such that unless a player actually disappears or hides behind something or someone, players should know where everyone in front of us on the basketball court, or the soccer field, is at all times [@schollChangeBlindnessBlindness2004]. Similarly, during driving many people seem to assume that they are aware of all hazards in their visual field. The fact that this is not accurate has been incorporated into driver education [@fisherCanNoviceDrivers2006] and, I imagine, sports education.

While change blindness demonstrations have dispelled naive beliefs about visual awareness of change, still people assume that if they are actively attending to a moving object, they will be aware of its features. As we have seen (Section \@ref(identity)), this is not true, although tracking something does make it more likely that a change will be detected. In a real-world task, albeit a simulated one (a driving simulation), this was evident in the results of @lochnerMultipleobjectTrackingDriving2014, who showed that changes were found more accurately and rapidly when a change was made to a target vehicle rather than a distractor vehicle.

Very few empirical studies have established strong links between real-world situations and laboratory MOT tasks or its underlying abilities. @bowersCanWeImprove2013 found that laboratory MOT performance did not predict driving test performance as well as either the Montreal Cognitive Assessment task, a trail-making task, or a subtest of a useful field-of-view task. The aforementioned driving simulator study by @lochnerMultipleobjectTrackingDriving2014 found that drivers were more accurate at localizing which of multiple lead vehicles braked if it was a tracking target, but there was no advantage in terms of braking response time. 

@mackenzieMultipleObjectAvoidance2021 used a multiple object avoidance task where the user used a mouse to control one of the balls, and the objective was to prevent it from colliding with the other balls. The task was reminiscent of Asteroids (Section \@ref(intro)). @mackenzieMultipleObjectAvoidance2021 found strong correlations with performance on a driving simulator and with years of driving experience. In an earlier paper, some of the same authors found that the MOA correlated better with driving performance than conventional MOT [@mackenzieLinkAttentionalFunction2017]. This may be because MOA includes active motor control, which is necessary for driving, but is not required for MOT.

In sports, some teams of researchers have repeatedly found evidence that MOT performance predicts in-game performance in soccer and other sports, and have also reported evidence that training on MOT tasks can enhance skill in sports. Unfortunately, the evidence for all this is not strong [@vaterCriticalSystematicReview2021]. Given the poor record of computer-based training tasks (sometimes called "brain training") in improving skills in other real-world domains, many will be skeptical that MOT training has benefits until more rigorous evidence is provided [@simonsBraintrainingProgramsWork2016].

<!--ADD @jarvisNeuroTrackerMultipleObject2022 NeuroTracker Multiple Object Tracking Ability Predicts Novice Performance on a Simulated Air Traffic Control Task-->
