# The biggest myth of object tracking {#biggestMyth}

What I consider to be the biggest myth about object tracking comprises three common misconceptions about what has been shown about object tracking:

1. There is a fixed capacity limit of about four or five objects that can be tracked, after which performance falls rapidly.
1. A softer version of the above claim: that performance generally falls to a particular level once the number of targets is increased to four or five objects. 
1. Different tasks show the same limit.

These three claims are widespread in the scholarly literature. <!--The issue of how many objects we can track is an important one for understanding tracking's role in natural behavior as well as the performance of laboratory tasks.--> One set of researchers, for example,  writing about the "object tracking system", stated: "One of the defining properties of this system is that it is limited in capacity to three to four individuals at a time" [@piazzaNeurocognitiveStartupTools2010]. Similarly, @fougnieDistinctCapacityLimits2006 wrote that "People’s ability to attentively track a number of randomly moving objects among like distractors is limited to four or five items"  <!--cites Pylyshyn Storm 1989-->  <!-- which cites Scholl's objects paper which makes the claim of 4 FINSTs but backs it up only with STM etc. type studies -->. This myth is sometimes perpetuated by papers with more ambiguous statements such as "participants can track about four objects simultaneously" [@vanderburgChangesNotDifferences2019]<!-- (see Cavanagh & Alvarez, 2005, for a review; Pylyshyn & Storm, 1988)--> Misconception #1, including the idea of a sharp fall in performance after a limit, seems to lie behind these sorts of statements. This is explcit in a take on the literature by @doranRoleVisualAttention2010, who wrote that "the main finding" of the object tracking literature is that "observers can accurately track approximately four objects and that once this limit is exceeded, accuracy declines precipitously." Vaguer statements in other papers, such as "researchers have consistently found that approximately 4 objects can be tracked"  [@alvarezHowManyObjects2007] and "people typically can track four or five items" @chesneyEvidenceSharedMechanism2011 <!--cites Pylyshyn 1989--> also bolster misconception #1 in the minds of readers.

To examine the evidence behind the claims of each of the quotations of the two preceding paragraphs, I have checked the evidence provided, and the papers cited, as well as the papers those cited papers cite. Each paper contains no evidence supporting the claim that performance decreases very rapidly once the number of targets is increased above some value. Instead, a gradual decrease in performance is seen as number of targets is increased, with no discontinuity, not even a conspicuous inflection point. For example, @oksamaMultipleObjectTracking2004, a paper that is sometimes cited in this context, examined performance with up to six targets <!--among twelve identical objects in total-->. After the five-second phase of random motion of the multiple moving objects, one object was flashed repeatedly and participants hit a key to indicate whether they thought it was one of the targets. The proportion of trials in which participants were wrong increased steadily with target size, from 3% incorrect with two targets, to 16% incorrect with six targets.<!--Note that even with six targets, participants were performing substantially better than would be expected if they could only track one or two and had to guess on the others.--> @pylyshynTrackingMultipleIndependent1988 may be the paper most frequently cited when a limit of four objects is claimed. But they also found a quite gradual decrease in performance (their Figure 1) as the number of targets was increased from one to five, and five was the most targets  they tested. Nowhere did @pylyshynTrackingMultipleIndependent1988 state that there is a value beyond which performance declines rapidly. Early in one paper, @pylyshynMultipleParallelAccess1994 wrote that people can track "at least four" objects, but later in the paper they did make a statement that could be interpreted as claiming there is a limit of four objects, writing that it is "possible to track about four randomly moving objects" [@pylyshynMultipleParallelAccess1994]. By 2007 when he published his book, "Things and Places: How the mind connects with the world", Pylyshyn wrote sentences like "And as long as there are not more than 4 or 5 of these individuals the visual system can treat them as though it had a concept of 'individual object'", implying a fixed capacity limit of four or five objects [@pylyshynThingsPlacesHow2007]. I suspect that this sort of slide toward backing a hard limit is caused in part by the desire for a simple story. It may also stem from an unconscious oversimplification of one's own data, and/or the theoretical commitment of Pylyshyn to the idea that tracking is limited by a set of discrete mental pointers.

I have so far addressed only one aspect of the claim (misconception #1) that there is a limit after which performance decreases rapidly. Another aspect of misconception #1 is that the limit is consistently found to be four or five. This isn't viable if there is no limit after which performance decreases rapidly, however one could retreat to misconception #2, the idea that tracking performance falls to some particular level at about four targets, even if this does not mark a hard limit (or even an inflection point). The particular performance level could be 75% correct, or a different criterion like the halfway point between ceiling and chance [@holcombeSplittingAttentionReduces2013], or the "effective number of items tracked", calculated by applying a formula to percent correct with the number of targets and distractors [@schollWhatVisualObject2001]. To be charitable, this may be what @alvarezHowManyObjects2007 meant when they wrote: "researchers have consistently found that approximately 4 objects can be tracked (Intriligator & Cavanagh, 2001; Pylyshyn & Storm, 1988; Yantis, 1992)", and the early studies they cited may be said to be consistent with this statement, even if not strongly supportive. <!-- Alvarez & Franconeri (2007)  "researchers have consistently found that approximately 4 objects can be tracked (Intriligator & Cavanagh, 2001; Pylyshyn & Storm, 1988; Yantis, 1992). The similarity of these estimates, combined with the frequency with which 4-item limits arise in other attention tasks, suggests the possibility that there is a “magical number 4” in visual attention (Cowan, 2001; Pylyshyn, 1989)."  neither said any such thing, it seems from my reading of those papers, e.g.  Pylyshyn & Storm 1988 only went up to 5 out of 10 and there was gradual decrease in performance all the way through. --> <!-- Papers I have checked for the 4-object claim: Cowan, 2001 claimed it for MOT, citing Pylyshyn et al. 1994, which does say "experiments showing that observers can simultaneously track some three to five identical target items" but then when he describes the studies he doesn't say they show that, even though in the discussion he says "One is that it is possible to track about four randomly moving objects" -->
<!-- In some cases the problem stems from Scholl Pylyshyn Feldman paper that devised the effective tracking capacity measure assuming 100% accuracy for one object and delivering a single number, often 4, for effective number tracked--> However, work published over the last fifteen years has revealed this apparent agreement across studies to be an artifact of researchers using similar display and task characteristics. That is, findings that approximately four objects can be tracked based on some performance criterion are just an accident of researchers using similar display parameters. One of the most important of these parameters is object speed.

The influence of object speed in tracking displays was made clear by @alvarezHowManyObjects2007, who tested participants with a display of sixteen wandering discs. When the speed of the discs was very high, participants could, at the end of a trial, correctly pick out the targets only if there were just a few targets. Conversely, for very slow speeds, participants could track up to eight targets accurately. This indicated that the truth of the idea that participants can track four objects is completely contingent on the speed of those objects. Additional evidence for this was found by others [@holcombeExhaustingAttentionalTracking2012; @feriaSpeedHasEffect2013]. Soon, other display parameters that strongly affect the number of objects that can be tracked were discovered, in particular object spacing [@franconeriEvidenceSpeedLimit2008; @holcombeObjectTrackingAbsence2014]. <!--As we will be discussed extensively in section \@ref(twoBrains), one aspect of spacing is that tracking performance can depend greatly on whether the targets are distributed between the left and right hemifields or instead are confined to one hemifield.--> 

In summary, it is incorrect to say that people can track about four moving objects, or even that once some (varying with circumstances) number of targets is reached, performance declines very rapidly with additional targets. The number that can be tracked is quite specific to the display arrangement, object spacing, and object speeds. If a researcher is tempted to write that "people can track about four objects", to reduce confusion, I think that they should stipulate that this refers to a particular combination of display characteristics and performance measures<!--something that I have almost never seen in the literature.-->

This issue of how to characterize a human cognitive limit has also bedeviled the study of short-term memory, a literature in which one of the most famous papers is titled "The magical number seven, plus or minus two: Some limits on our capacity for processing information" [@millerMagicalNumberSeven1956]. Two dozen working memory researchers convened in 2013 to highlight empirical "benchmarks" for models of working memory. One issue they considered was how to talk about how many items people can remember. In the paper that they published in 2018, the researchers pointed out that "observed item limits vary substantially between materials and testing procedures" [@oberauerBenchmarksModelsShortterm2018]. They suggested, however, that much of this variability could be explained by humans' ability to store groups of items as "chunks", and thus the group endorsed a statement that there is a limit of "three to four chunks" [@cowanMagicalNumberShortterm2001a]. In the case of short-term memory, then, the observed variability in experiments' results can potentially be explained by a common underlying limit of three to four chunks that manifests as different observed item limits depending on circumstances (in particular, the opportunity for chunking). Evidently there is no simple task parameter unrelated to chunking opportunity, analogous to object speed in the case of MOT, that smoothly varies through a wide range how many items people can remember.

Perhaps the leading candidate for a firm capacity limit in cognitive psychology is the "subitizing" or near-exact numerosity perception limit. For subitizing, there really does seem to be an inflection point in accuracy when the number of objects shown goes from less than four to more than four [@revkinDoesSubitizingReflect2008]. Four objects and fewer is frequently referred to as the "subitizing range", with performance approximately as good for rapidly counting four objects as it is for two or one. Note that this is very different than in tracking, for which speed thresholds decline rapidly from one to two targets, as well as to three and four. For visual working memory, which as we mentioned several experts have characterized as being limited to three or four chunks, whether there is an inflection after four objects, or at any point, remains debated [e.g. @robinsonThereCapacityAssessing2020].

In the case of MOT, it remains possible that researchers will be able to identify a set of circumstances that consistently yield a mean tracking limit, in the modal human, of three or four targets, if "limit" is defined as performance falling to a particular level on some performance metric. Probably these circumstances will simply be certain spacings, speeds, object trajectories, and number of objects in a display. It would be nice if some underlying construct, the counterpart of memory's "chunks", would be identified to explain how performance changes when other circumstances are used. That would constitute real progress in theory development. However, I don't see anything like that in the literature currently.

<!-- At this point,  to defend the claim that people can track "about four objects" is to suggest that the studies that have found four targets to be the number that can be tracked . Is there something special about  these speeds. Nobodh justified them with ecological analysis-->

## Claim #3: Different tasks, same limit?

Even after discarding the idea that there is a particular number of objects that one can track, misconception #3 could still be viable. This claim is frequently tangled up in the myth reviewed above, and sometimes stated as "there is a magical number four". After discarding the idea of a number, four, that does not vary with circumstances, there remains the notion that different tasks have the same number-of-objects limit when tested in comparable circumstances. For example, @bettencourtSharedFilteringProcesses2011 stated that visual short-term memory and MOT show "an equivalent four-object limit", and @piazzaNeurocognitiveStartupTools2010 similarly claimed that visuo-spatial short-term memory, ultra-rapid counting (subitizing), and multiple object tracking share a common limit of "three or four items".

<!--I don't know of any work that has used a display of multiple objects moving at a particular speed and found a similar capacity limit for multiple tasks including MOT.--> So far, there is no good evidence that object tracking has the same limit in some sense as visual working memory and subitizing. Ideally this could be assessed by measuring the limits for all three tasks using the same stimuli, but it is unclear how to equate the information available across tasks. Especially difficult is comparing performance with the briefly-presented static stimuli used in subitizing and working memory tasks to the extended exposures of moving stimuli needed to assess object tracking. A stronger understanding of the processes mediating tracking would be required to model performance of the two tasks using a common framework via which they could be compared at an underlying psychological construct level. However, another approach is to measure the tasks of interest in large numbers of individuals and see whether the different task limits strongly co-vary between individuals. The findings from this approach are reviewed in section \@ref(abilities).

<!-- https://psyc2016.whatanimalssee.com/bottlenecks.html#a-bottleneck-for-object-judgments -->

<!--Working off the dominant framing, that each person does have a specific number of targets they can track which determines percent correct for each level of number of targets, some MOT researchers report what @schollWhatVisualObject2001 called the "effective number of items tracked". The associated formula, refined by @hullemanMathematicsMultipleObject2005a allows researchers to calculate the effective number of items tracked based on accuracy in an individual condition, given the number of targets and distractors in that condition. This does provide a useful summary of the data, but researchers should take more care to avoid taking it literally.--> <!--Still, it does seem that the number four pops up more than would be expected if these abilities were unrelated. -->

It's very disappointing how prevalent the myth of a limit of four to five targets has become. It makes me worry that the way we do science, or the way we do this kind of science, does not result in the commumity of researchers knowing the basics of what the evidence supports, at least not in a reasonable amount of time. But that is a topic for another occasion. Given that tracking performance does depend greatly on circumstances and falls gradually rather than displaying a discontinuity at a particular target number, what are the implications for how tracking works?

<!--In this Section, we discussed three common misconceptions about what has been shown about object tracking. The one that we have just discussed is that different tasks show the same limit. -->

<!--This may actually be true, but I know of no research that have used the same display and task settings to adequately back this up.--> 


