# Two brains or one? {#twoBrains}

Most of the public know little about the brain, but have heard the phrases "left brain" and "right brain". Understandably, the public assumes that this separation has major consequences for learning. This assumption is exploited by a major industry of pseudoscientific education consultants and brain training programs, with programs they refer to as "left brain versus right brain" training [@kroezeBrainGymPseudoscientific2016] and the like.

The truth is that while early sensory processing is very specific to the two halves of the cortex, more cognitive functions such as explicit learning benefit from a very tight integration. Our conscious experience is one of attending easily to objects in any part of the visual field, left or right. We experience no discontinuity when the movement of our eyes, or of an object, cause an object to shift from one hemifield, where it is processed predominantly by one hemisphere, to the other hemifield. Communication between the two hemispheres happens rapidly and continuously, and there is no good evidence that exercises designed to insure both hemispheres process stimuli have any benefit for learning. 

For those extraordinarily rare individuals who have had some connections between their hemispheres cut ("split brain" patients), the hemispheres act more independently. Indeed, for tasks such as searching for a target among many distractor objects, it is better to distribute the distractors across the two hemifields. Spreading the load in this way yields a large benefit for search, suggesting that both hemispheres can search independently and simultaneously [@luckIndependentAttentionalScanning1994a]. But for normal individuals, no such advantage is seen, suggesting that the processes that evaluate each stimulus for whether it is the target are well integrated across the hemispheres [@luckIndependentHemisphericAttentional1989].

This is not to say that the hemispheres are equivalent. They do specialize in different functions. For example, the left hemisphere in most people seems to specialize in language functions including reading, whereas the right hemisphere is better at recognizing faces. A behavioral consequence is that response times for a face recognition task are slightly faster when the face is presented in the left hemifield (to the right hemisphere) whereas the opposite is found for word reading [@rizzolattiOppositeSuperioritiesRight1971]. However, with extended time to process a stimulus, these behavioral asymmetries, already small, diminish and are hard to detect, as the two hemispheres collaborate on processing a stimulus presented to either hemifield.

There is another subtle effect of the hemispheric division of cortex. In some tasks involving two simultaneously-presented stimuli, higher performance is found when each stimulus is presented in a different hemifield rather then presenting them both in the same hemifield. For example, the reporting of two briefly-presented digits is more accurate when the digits are presented in different hemifields than in the same hemifield [@dimondUseTwoCerebral1971].  

These effects tend to be small.

@holtBilateralAdvantageMaintaining2015 found BLAH BLAH



## The remarkable 

, such that presenting a word, for example, yields slightly greater accuracy 

In normal individuals, there are some tasks for which there is evidence of some independent functioning, in the form of a behavioural advantage for presenting the relevant stimuli split across the hemifields rather than presenting them to one hemifield. An early demonstration of this was by 

normal individuals act much more as if their hemispheres are working independently.

In visual short-term memory tasks, people perform a good deal better when the stimuli are spread across both the left and right hemifields rather than all presented to the left hemifield or to the right hemifield [@delvenneVisualShorttermMemory2012]. The reason, it is believed, is that there is some sort of resource that is specific to each hemifield. It is better, then, to spread one's load, rather than burdening one hemisphere more than the other. If the processes that limit memory performance were entirely specific to the hemispheres, then once people's limit for remembering objects presented to one hemifield were reached, one could add more objects to the other hemifield without any cost for the proportion of objects remembered. Instead, though, the hemifield advantage is only partial. There are a few tasks, however, for which the hemifield advantage seems to be complete, and multiple object tracking is one.

@delvenneCapacityVisualShortterm2005: "a color and spatial location change detection task, in which the items were displayed either in the two visual fields or in the same hemifield. The data revealed that only memory capacity for spatial locations and not colors increased when the items were separated between the two visual fields. These findings support the view of VSTM as a chain of capacity limited operations where the spatial selection of stimuli, which dominates in both spatial location VSTM and MOT, occupies the first place and shows independence between the two fields."


@alvarezIndependentResourcesAttentional2005 were the first to show that distributing objects to two hemifields rather than one could, essentially, double performance, as if two brains were doing the task rather than one...

@hudsonHemifieldEffectsMultiple2012 multiple identity tracking , found a hemifield advantage: " Contrary to expectations, a bilateral advantage was still observed, though it was not as strong as when observers were not required to remember the identities of the targets. This finding is inconsistent with the only model of multiple identity tracking (Oksama & Hyönä, 2008, Cognitive Psychology, 56, 237-283), so we present an alternative account."

@strongHemifieldspecificControlSpatial2019

RIGHT HEMIFIELD IS BETTER @holcombeObjectTrackingAbsence2014 (Figure A2), Battelli


### Quadrants

Carlson et al. found evidence for quadrants. Has this been replicated? And @strongHemifieldspecificControlSpatial2019 found a cost for crossing the vertical midline but not the horizontal midline. So now we know that the cross-hemisphere cost does not occur for quadrants. 

