---
title: "UCSDbrownBag"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- I was pretty distracted by the need for open access, open science, and the problem of the replication crisis over the last 10 years,
but now I've made up for it by writing a book 40,000 words -->

Basic demo

Linares Vaziri demo

This will make the case for tracking being much more important than people realize.  but you can't even perceive spatial relationships.

At the same time, what little most psychology researchers think they know about object tracking is *wrong*. Can't blame you for that, because plenty of misinformation has been spread by tracking researchers themselves.

There's just no evidence for any sort of discrete limit, the way there is in subitizing, or dare I say visual working memory. 

I suspect a lot of people in this audience will deeply appreciate that thanks to work by Tim Brady and John Wixted finding that you don't need discrete slots or anything like that to explain VWM.  But I'd love to hear any pushback on this point. I know, Tim and John are very intimidating.. I'll move on.

tracking.whatanimalssee.com

# Individual differences

High split-half reliability (>0.8), unlike other cognitive tasks.
<!--Headed to Portland-->

Only a handful of proper individual-difference studies.

A large set of studies with "Neurotracker" and other products, looking at correlations and also training, almost all with shoddy research designs.

# Tracking operates on objects

People think they know this from static objects but they don't. Effect is small and may be mostly false positives.

We don't know why elongation and contraction hurts so much.

# Hemifield specificity

The most important discovery, yet sadly neglected and unexploited. Is this new tracking result about tracking or about limits on cognition?

The way to distinguish from C~1 processes.

## Unitary cognition (C≈1 processes)

Most researchers never talk about this, which pisses me off. 

Tracking may benefit from two resources. One is a resource that can process multiple targets simultaneously, even if it does so more poorly than if there is only one target. A second resource that likely benefits tracking has a capacity of only one target. This reflects a unitary focus of attention that has an approximate capacity of only one. It is the same set of processes that limits us to doing only one 2-digit mental multiplication problem at a time. When applied to tracking, it means you can apply your full intelligence and powers of reasoning to tracking that target, for example to use what you've learned about object trajectories to predict future positions.

The scenario that there are two resources that can benefit tracking makes interpreting the results of experiments complicated. It makes a lot of the results trumpeted by tracking papers uninteresting. Many papers that come out of the experimental psychology tradition (as opposed to psychophysics, which is more quantitative) content themselves with showing that something is true, that a factor matters for performance, p < .05. Never mind how much it matters, the effect size. This kind of thinking is a real problem across psychology, and in tracking, it leads to me wanting to drag the paper straight into the recycle bin.

# Speed? 

The trade-off between speed and number of targets implies that it's resource-intensive. If you know your classics, you'll recognize this concept as being the same as "resource-limited" in Norman & Bobrow 1975.

or temporal frequency?


# Predictive brain?

# Objects in motion

Motion silencing

# Serial or parallel?

Seems like limited-capacity parallel.

But conventional tests don't really probe that.

There's no work on hemifield specificity of sampling.


